services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: javanote
      POSTGRES_USER: javanote
      POSTGRES_PASSWORD: javanote
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: javanote
      MONGO_INITDB_ROOT_PASSWORD: javanote
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: