server:
  port: 8080

spring:
  application:
    name: core-api
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/javanote
    username: javanote
    password: javanote
  jpa:
    hibernate:
      ddl-auto: validate
  mongodb:
    uri: mongodb://javanote:javanote@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/javanote?authSource=admin
    representation:
      uuid: standard
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


javanote:
  jwt:
    secret: ${JWT_SECRET:dev-only-secret-change-me-please-32-bytes-min}

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, caches, info
info:
  app:
    name: ${spring.application.name}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t] %X{requestId}/%X{userId}){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"